CREATE TABLE [dbo].[Users]
(
    [Id] INT IDENTITY(1,1) NOT NULL, 
    [CompanyCode] VARCHAR(5) NULL, 
    [EmployeeNo] VARCHAR(10) NOT NULL, 
    [FirstName] VARCHAR(25) NULL, 
    [LastName] VARCHAR(25) NULL, 
    [Status] INT NOT NULL, 
    [Password] VARCHAR(20) NULL,
    [CreatedOn] DATETIME NOT NULL, 
    [CreatedBy] CHAR(25) NOT NULL, 
    [UpdatedOn] DATETIME NULL, 
    [UpdatedBy] CHAR(25) NULL,
    PRIMARY KEY CLUSTERED
    (
      [Id] ASC
    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
    ON [PRIMARY]
)

